# Generated by Django 4.0.4 on 2022-05-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.IntegerField()),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('Phone_number', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Martial_status', models.CharField(max_length=15)),
                ('Vacation_Days', models.IntegerField(blank=True, null=True)),
                ('Vacation_Days_approved', models.IntegerField(blank=True, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('Birthday', models.DateField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Vacation_from', models.DateField()),
                ('Vacation_to', models.DateField()),
                ('Reason', models.CharField(max_length=400)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee')),
            ],
        ),
    ]
