# Generated by Django 4.0.4 on 2022-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vacation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
