# Generated by Django 4.0.4 on 2022-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_Id',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
