# Generated by Django 4.0.4 on 2022-05-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_Id',
            field=models.IntegerField(),
        ),
    ]
