# Generated by Django 4.0.4 on 2022-05-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='Name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='Reason',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='Vacation_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='Vacation_to',
            field=models.DateField(null=True),
        ),
    ]
