# Generated by Django 4.0.4 on 2022-05-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_vacation_id_alter_vacation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='Id',
        ),
    ]
