# Generated by Django 4.0.4 on 2022-05-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vacation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='Id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
